# Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely need to edit after that.
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'jekyll serve'. If you change this file, please restart the server process.
#
# # Site settings
title:
  en: Docker Sevilla 
  es: Docker Sevilla
email: docker@irespaldiza.com
description:
  en: Docker Sevilla  WebSite
  es: Pagina de Docker Sevilla
  index:
  en:
  es: indice.html
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dockersevilla.github.io" # the base hostname & protocol for your site
twitter_username: dockersevilla
github_username: dockersevilla
linkedin_username: groups/12076213
facebook_username: 287339491771307 
# Build settings
markdown: kramdown

theme: jekyll-theme-dinky